### PR TITLE
typo fixes

### PR DESCRIPTION
**Pull request by ThomasWaldmann**

### CODE REVIEW

**Comment by ThomasWaldmann** [comment]
I compiled and executed the code after making the changes, it still works.

Also I used grep to hopefully find all places that needed fixing. :-)

**Comment by adamgreen** [comment]
Thanks for the fixes. Much appreciated.

The license for this project is GPL v2. Do you still want me to merge this PR under this reciprocal license?

**Comment by ThomasWaldmann** [comment]
Yes, I am fine with GPL v2 also.

**Comment by adamgreen** [comment]
Excellent! I have merged it.

Thanks again for the corrections.

**Pull request merged**
